# Histopathologic Cancer Detection using Deep Learning

### Importamos las librerias necesarias para el analisis de las imágenes y la realización de las predicciones

In [ ]:
import numpy as np 
import pandas as pd
from glob import glob 
from skimage.io import imread
import os
from pathlib import Path
import keras.backend as K

### Armamos el dataframe con el conjunto de datos de entrenamiento

In [68]:
train_dir = '../iis-project/train'
df = pd.DataFrame({'path': glob(os.path.join(train_dir,'*.tif'))})
labels = pd.read_csv("../iis-project/train_labels.csv")
df['label'] = labels['label']
df.head(10)


path  label
0  ../iis-project/train/052fddb3940ec9f4b9d7d0925...      0
1  ../iis-project/train/70e728f78f937dfb16e9867e8...      1
2  ../iis-project/train/9b59ba4f1bb5ea63828450fdc...      0
3  ../iis-project/train/e0dfb12d1e7116ffa26b7a967...      0
4  ../iis-project/train/ea62cbcd62f4438f47902b1bf...      0
5  ../iis-project/train/cc5be12926073b97cb9d5146e...      0
6  ../iis-project/train/5bf198b5f0732515d0d402a85...      1
7  ../iis-project/train/09e441c22952ad49a8a4acb81...      1
8  ../iis-project/train/6dfe8a3ca29bff5a2bb108ec2...      0
9  ../iis-project/train/7e4b77f241ef3d8d21b188b75...      0

### Se selecciona una muestra de cada etiqueta

           
    Se crean 2 dataframes, uno para cada etiqueta, cada uno de ellos con 10000 elementos ya que tomar en cuenta todo el conjunto no resulta práctico por las limitaciones de recursos fisicos como memoria RAM y/o disco. A partir de estos dataframes se crea uno nuevo que contenga el conjunto de datos reducido.

In [104]:
sample_label0 = df[df.label == 0].sample(10000, random_state=50)
sample_label1 = df[df.label == 1].sample(10000, random_state=50)


reduced_df = pd.DataFrame(pd.concat([sample_label0, sample_label1]))
reduced_df

path  label
14294   ../iis-project/train/49d061af6863059d9afabf7e2...      0
83175   ../iis-project/train/26891da24730bc1c924b1ad13...      0
74374   ../iis-project/train/39f9bd4975b0b95f840450a91...      0
26984   ../iis-project/train/d9b9cd49eb89bb553f88f183a...      0
57505   ../iis-project/train/11f6b098f3fb28e0db9698ac8...      0
197135  ../iis-project/train/9fd8451bad7342aa3ba77dca8...      0
31167   ../iis-project/train/3312e73673436be1ea66f1bc1...      0
77031   ../iis-project/train/bbaf303a6a3ac009b0bd91d76...      0
70712   ../iis-project/train/a67746c73686d14cf97a99811...      0
26579   ../iis-project/train/061007f8eb6746ccc272a8c5f...      0
45050   ../iis-project/train/5c4b02f573e04ba8d050a40b6...      0
111679  ../iis-project/train/6884ad7446e4256692b6799df...      0
65743   ../iis-project/train/427344232a9e6700902963597...      0
64886   ../iis-project/train/a7380f51c3016547dec2dc871...      0
129197  ../iis-project/train/70d345163a6bac8977338b2a1...      0
62894   ../iis-project/train/30ce72fe1c9c61588b334e90c...      0
161007  ../iis-project/train/90da3e0f3a0ff1be7fdc64675...      0
10854   ../iis-project/train/5342d32892ca2b78d63a40148...      0
197521  ../iis-project/train/f0797f88504d57d08d9d57737...      0
188898  ../iis-project/train/3939e1b9d33ad83d17319077e...      0
190778  ../iis-project/train/97938cee7b1d3556738262f7d...      0
117349  ../iis-project/train/d298e2c0d2590197628774116...      0
117198  ../iis-project/train/be106742e1609d02167b68bad...      0
104417  ../iis-project/train/3d08079b2160bcfbda42ba509...      0
92517   ../iis-project/train/db200a482fdd21bf1307462da...      0
79573   ../iis-project/train/de587aaf6bff8dc744df532e7...      0
13221   ../iis-project/train/03588989b31ed130e45d786af...      0
47152   ../iis-project/train/8daf204a5bd35c082d7279897...      0
74888   ../iis-project/train/f52b9c997d75fa7b1ea2b9624...      0
150391  ../iis-project/train/f6b98fe38195db1f37ecaeeae...      0
...                                                   ...    ...
58722   ../iis-project/train/cfd7df0082a4739c9f844909b...      1
33964   ../iis-project/train/fde0fb6fc53fc6b74f21f507c...      1
24171   ../iis-project/train/964fd5c68590f556664809764...      1
177608  ../iis-project/train/747af6582c3e7f94142235253...      1
50620   ../iis-project/train/19eeb25f51a989d92c70898c2...      1
8153    ../iis-project/train/ebe5bd305f35c4690b3171c00...      1
54086   ../iis-project/train/4cc1b01d28de2bdaa5ec73e56...      1
197279  ../iis-project/train/8fff6319bb14b62be57a9b968...      1
40851   ../iis-project/train/ab562a3d45a6cfe4c727342c7...      1
151675  ../iis-project/train/b3c5e532804edf04e52782d7d...      1
49978   ../iis-project/train/7f76a8c943af94281ad7db42e...      1
9277    ../iis-project/train/cf568761569226cc36c30f08b...      1
174638  ../iis-project/train/5006135b8d2eb1ed37b7cbb91...      1
191014  ../iis-project/train/8465d0f3a717771c422ab1271...      1
194543  ../iis-project/train/9d9f93b30c8b7407791039102...      1
32159   ../iis-project/train/2910ddc4ddf2c9d967278d072...      1
200449  ../iis-project/train/823f07f75d30fde22033ca3a8...      1
204914  ../iis-project/train/e675ef93f2721123fe0139162...      1
186315  ../iis-project/train/e1422161a5268af944d78822e...      1
195746  ../iis-project/train/5786d77195ac58a13b26bd6f8...      1
27358   ../iis-project/train/b00a2a4ed2a1164a196c9768c...      1
83825   ../iis-project/train/ecf2ce140aa47c9a78cbe064a...      1
117477  ../iis-project/train/346dc134f831463dc7cecea2d...      1
78069   ../iis-project/train/cf3db84ef3ba1a2e88ab6a07e...      1
194490  ../iis-project/train/c59b6a88e65abbf127a97432b...      1
33315   ../iis-project/train/f81cf6397a2971e1c47c17eb5...      1
65051   ../iis-project/train/95fe7b806c46bd76c04201f68...      1
136304  ../iis-project/train/b3bdfb1d6ae2ce9b64223103f...      1
130363  ../iis-project/train/7edead7418e66ceec2ab3234a...      1
186679  ../iis-project/train/c1dfb61df2b00fe62cd60af95...      1

[20000 rows x 2 column

In [79]:
sample_label0.shape
sample_label1.shape
reduced_df.shape

reduced_df['image'] = reduced_df['path'].map(imread)
reduced_df



path  label  \
14294   ../iis-project/train/49d061af6863059d9afabf7e2...      0   
83175   ../iis-project/train/26891da24730bc1c924b1ad13...      0   
74374   ../iis-project/train/39f9bd4975b0b95f840450a91...      0   
26984   ../iis-project/train/d9b9cd49eb89bb553f88f183a...      0   
57505   ../iis-project/train/11f6b098f3fb28e0db9698ac8...      0   
197135  ../iis-project/train/9fd8451bad7342aa3ba77dca8...      0   
31167   ../iis-project/train/3312e73673436be1ea66f1bc1...      0   
77031   ../iis-project/train/bbaf303a6a3ac009b0bd91d76...      0   
70712   ../iis-project/train/a67746c73686d14cf97a99811...      0   
26579   ../iis-project/train/061007f8eb6746ccc272a8c5f...      0   
45050   ../iis-project/train/5c4b02f573e04ba8d050a40b6...      0   
111679  ../iis-project/train/6884ad7446e4256692b6799df...      0   
65743   ../iis-project/train/427344232a9e6700902963597...      0   
64886   ../iis-project/train/a7380f51c3016547dec2dc871...      0   
129197  ../iis-project/train/70d345163a6bac8977338b2a1...      0   
62894   ../iis-project/train/30ce72fe1c9c61588b334e90c...      0   
161007  ../iis-project/train/90da3e0f3a0ff1be7fdc64675...      0   
10854   ../iis-project/train/5342d32892ca2b78d63a40148...      0   
197521  ../iis-project/train/f0797f88504d57d08d9d57737...      0   
188898  ../iis-project/train/3939e1b9d33ad83d17319077e...      0   
190778  ../iis-project/train/97938cee7b1d3556738262f7d...      0   
117349  ../iis-project/train/d298e2c0d2590197628774116...      0   
117198  ../iis-project/train/be106742e1609d02167b68bad...      0   
104417  ../iis-project/train/3d08079b2160bcfbda42ba509...      0   
92517   ../iis-project/train/db200a482fdd21bf1307462da...      0   
79573   ../iis-project/train/de587aaf6bff8dc744df532e7...      0   
13221   ../iis-project/train/03588989b31ed130e45d786af...      0   
47152   ../iis-project/train/8daf204a5bd35c082d7279897...      0   
74888   ../iis-project/train/f52b9c997d75fa7b1ea2b9624...      0   
150391  ../iis-project/train/f6b98fe38195db1f37ecaeeae...      0   
...                                                   ...    ...   
58722   ../iis-project/train/cfd7df0082a4739c9f844909b...      1   
33964   ../iis-project/train/fde0fb6fc53fc6b74f21f507c...      1   
24171   ../iis-project/train/964fd5c68590f556664809764...      1   
177608  ../iis-project/train/747af6582c3e7f94142235253...      1   
50620   ../iis-project/train/19eeb25f51a989d92c70898c2...      1   
8153    ../iis-project/train/ebe5bd305f35c4690b3171c00...      1   
54086   ../iis-project/train/4cc1b01d28de2bdaa5ec73e56...      1   
197279  ../iis-project/train/8fff6319bb14b62be57a9b968...      1   
40851   ../iis-project/train/ab562a3d45a6cfe4c727342c7...      1   
151675  ../iis-project/train/b3c5e532804edf04e52782d7d...      1   
49978   ../iis-project/train/7f76a8c943af94281ad7db42e...      1   
9277    ../iis-project/train/cf568761569226cc36c30f08b...      1   
174638  ../iis-project/train/5006135b8d2eb1ed37b7cbb91...      1   
191014  ../iis-project/train/8465d0f3a717771c422ab1271...      1   
194543  ../iis-project/train/9d9f93b30c8b7407791039102...      1   
32159   ../iis-project/train/2910ddc4ddf2c9d967278d072...      1   
200449  ../iis-project/train/823f07f75d30fde22033ca3a8...      1   
204914  ../iis-project/train/e675ef93f2721123fe0139162...      1   
186315  ../iis-project/train/e1422161a5268af944d78822e...      1   
195746  ../iis-project/train/5786d77195ac58a13b26bd6f8...      1   
27358   ../iis-project/train/b00a2a4ed2a1164a196c9768c...      1   
83825   ../iis-project/train/ecf2ce140aa47c9a78cbe064a...      1   
117477  ../iis-project/train/346dc134f831463dc7cecea2d...      1   
78069   ../iis-project/train/cf3db84ef3ba1a2e88ab6a07e...      1   
194490  ../iis-project/train/c59b6a88e65abbf127a97432b...      1   
33315   ../iis-project/train/f81cf6397a2971e1c47c17eb5...      1   
65051   ../iis-project/train/95fe7b806c46bd76c04201f68...      1   
136304  ../iis-project/train/b3bdfb1d6ae2

In [99]:
print(reduced_df['image'][45050])
reduced_df.shape

[[[202 139 166]
  [208 147 178]
  [148  91 124]
  ...
  [164 117 163]
  [173 124 171]
  [ 99  47  95]]

 [[174 118 145]
  [184 129 160]
  [186 134 170]
  ...
  [ 85  39  85]
  [114  64 113]
  [118  68 117]]

 [[251 202 231]
  [185 138 170]
  [188 142 179]
  ...
  [111  65 112]
  [ 60  14  61]
  [161 115 162]]

 ...

 [[186 143 153]
  [233 189 204]
  [153 104 125]
  ...
  [103  51  97]
  [196 145 186]
  [112  62 100]]

 [[238 201 209]
  [238 198 209]
  [199 156 175]
  ...
  [124  68 113]
  [164 112 151]
  [198 146 184]]

 [[255 231 238]
  [219 183 195]
  [184 142 162]
  ...
  [125  69 114]
  [139  84 124]
  [143  91 127]]]


(20000, 3)